### ISSUE TITLE
No module named 'winrandom'

### ISSUE THREAD

**Issue by acclea** [pycrypto/pycrypto#315]
when i used  [pycrypto] , the program had this " ModuleNotFoundError: No module named 'winrandom' " warning

i try to fix [ nt.py ], but i can not found a file named  "winrandom"

or i change 

import winrandom

to

from Crypto.Random.OSRNG import winrandom

that new warning occur

AttributeError: module 'time' has no attribute 'clock'

env === python3.9

thanks

**Comment by aminsoheyli** [comment]
This project is  dead! #173 

Use [pycryptodome](https://github.com/Legrandin/pycryptodome) or [cryptography](https://github.com/pyca/cryptography).

**Comment by acclea** [comment]
> This project is dead! #173
> 
> Use [pycryptodome](https://github.com/Legrandin/pycryptodome) or [cryptography](https://github.com/pyca/cryptography).

thank you
